site_name: Test
repo_url: https://github.com/kuanchoulai10/data-mesh
repo_name: Data Mesh Side Project
nav:
  - Demo: demo.md
  - Demo2: demo2.md
  - Demo3: demo3.md
  - Demo4: demo4.md

theme:
  name: material
  palette:
    primary: brown
    accent: amber
  language: zh-TW
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js